### ISSUE TITLE
Elect a new project lead 👨‍🔧

### ISSUE THREAD

**Issue by sbernard31** [eclipse-wakaama/wakaama#616]
I was mainly elected to help to relaunch the project ([for more details](https://projects.eclipse.org/projects/iot.wakaama/elections/election-simon-bernard-project-lead-eclipse-wakaama)), so at short/midterm the team will need a more active/technically implied project lead.

FMPOV, the team performs well :+1: and it's maybe time to discuss about this. 
To be honest, I'm a bit jealous I would like the same kind of Team for Leshan :grin:.

Just in case you wonder, Eclipse project can have several project lead, so I will probably keep my project lead status and could help if needed.

**Comment by qleisan** [comment]
You have done a great job so far. Knowledgeable, supportive, friendly, I (we) hope you stay involved even if somebody else steps up .

**Comment by hannestschofenig** [comment]
What is the status on finding a new project lead?

**Comment by tuve** [comment]
I can only concur with @qleisan , thank you for a great job @sbernard31

**Comment by sbernard31** [comment]
Thx guys, I really appreciate it. :pray: 

> What is the status on finding a new project lead?

I guess we need a name, then a I will be able to launch an election. 

So team, let me know who you would like to have as project lead or who is comfortable with the idea to take this role. 

I share here some resources about what means being a project lead : 
> **Project Lead**
>
>   The project lead is more of a position of responsibility than one of power. The project lead is immediately responsible for the overall well-being of the project. They own and manage the project’s development process, coordinate development, facilitate discussion among project committers, ensure that the Eclipse IP policy is being observed by the project and more.
>   A Project Lead, the first level in the Project Leadership Chain, is responsible for the overall well-being of a specific Project and serves as the primary liaison between that Project and the EMO.

and : 
- https://www.eclipse.org/projects/dev_process/#4_6_2_PL
- https://waynebeaton.wordpress.com/2010/03/09/project-leadership/

Historically, it was @sbertin-telular , @rettichschnidi who made this "revival" possible.
Regarding past involvement, I guess @sbertin-telular would have been an natural choice but he will not be able to do that. (https://github.com/eclipse/wakaama/issues/572#issuecomment-811960168)
So maybe @rettichschnidi could be a possible choice ?

Of course all other propositions are welcome.
Team, let me also know if you have any concern about this ? 
:slightly_smiling_face:

**Comment by hannestschofenig** [comment]
@rettichschnidi How do you think about the proposal of becoming a new project lead?

**Comment by rettichschnidi** [comment]
I gave this quite some thoughts and came to the conclusion that I could (currently) not live up to the responsibilities attached to this role.
Mainly because I am, for quite some months already, not involved in any Wakaama related work in my day job. This will change in 2022, but for now, I am simply not able to invest enough time.

**Comment by sbernard31** [comment]
So what should we do ? 
Is there someone else which would like to take the role ? 
Or do we wait for begin of 2022  for @rettichschnidi  to give us an update ?

**Comment by sbernard31** [comment]
@rettichschnidi, I see the team and especially you are very active again. :slightly_smiling_face: 
Let me know if you think it's time for project lead election ?

**Comment by sbernard31** [comment]
@rettichschnidi, @LukasWoodtli, @mlasch

Maybe it's time to talk again about new project lead election ? 

@LukasWoodtli involve a lot in the project and would probably be a good choice?

(https://github.com/eclipse-wakaama/wakaama/issues/616#issuecomment-924959633 is still relevant to read before)

**Comment by LukasWoodtli** [comment]
@sbernard31 I am not opposed to the idea of being the project lead for Wakaama.
We also discussed it internally and think this would be a good option.

I don't know yet the full set of tasks and responsibilities associated with this role. But I'm sure it will be manageable with yours (and others) help.

As a starter: how do we initiate the election of a new project lead?

**Comment by sbernard31** [comment]
>  I am not opposed to the idea of being the project lead for Wakaama.
>  We also discussed it internally and think this would be a good option.

Great !

> I don't know yet the full set of tasks and responsibilities associated with this role. 

You can have a quick look at : https://github.com/eclipse-wakaama/wakaama/issues/616#issuecomment-924959633
This will give you the general idea. 

>  I'm sure it will be manageable with yours (and others) help.

:+1:  I will continue to look at the project and will help you when necessary. 

> As a starter: how do we initiate the election of a new project lead?

This is more or less like "Nominate de Committer".  (see https://github.com/eclipse-wakaama/wakaama/issues/745#issuecomment-1853547635)

**I will try to initiate the process myself this week.**

**Comment by sbernard31** [comment]
You should be able to follow vote at : https://projects.eclipse.org/projects/iot.wakaama/elections/election-lukas-woodtli-project-lead-eclipse-wakaama

**Comment by jvermillard** [comment]
I just voted, but I never received an email notification from the Eclipse "portal." Is it just me?

**Comment by boaks** [comment]
I received e-mails via iot-pmc and wakaama-dev, both yesterday at 18:09.

**Comment by jvermillard** [comment]
thanks, I need to check they are probably using my old email

**Comment by sbernard31** [comment]
Vote is done. @LukasWoodtli  is now [Project Lead](https://projects.eclipse.org/user/18576) on Wakaama ! Congrats :tada: :clap:  !

(I updated : https://github.com/eclipse-wakaama/wakaama/issues/488)
