### ISSUE TITLE
make problems with wakaama client

### ISSUE THREAD

**Issue by yan0727** [eclipse-wakaama/wakaama#634]
this is operate report:

                    [root@IoT-Apps lwm2m]# make
                    [  2%] Building C object CMakeFiles/lwm2mclient.dir/object_test.c.o
                    /opt/wakaama/examples/client/object_test.c: In function ‘get_test_object’:
                    /opt/wakaama/examples/client/object_test.c:562:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
                                 for (int j = 0; j <= i; j++) {
                                 ^
                    /opt/wakaama/examples/client/object_test.c:562:13: note: use option -std=c99 or -std=gnu99 to compile your code
                    make[2]: *** [CMakeFiles/lwm2mclient.dir/object_test.c.o] Error 1
                    make[1]: *** [CMakeFiles/lwm2mclient.dir/all] Error 2
                    make: *** [all] Error 2

**Comment by rettichschnidi** [comment]
Please reopen in case this is still a problem.
