### ISSUE TITLE
Support of send operation for single resource data with TLV format ?

### ISSUE THREAD

**Issue by EmbGangsta** [eclipse-wakaama/wakaama#761]
I dont know if it's normal or a bug, but when I run the wakaama client demo with the "send 123 /3/0/9" command, I can see today the supported format is only SENML JSON or SENML CBOR.

Would it be possible to support TLV as well ?

**Comment by EmbGangsta** [comment]
Ok in that case that makes sense, thank you for confirmation.

Is the SenML CBOR more efficient than TLV in term of data size ?

**Comment by sbernard31** [comment]
I don't know. :shrug: 

**TLV** is a binary format so it should be pretty efficient.
In **LWM2M v1.0.x**, it was the only binary format and probably the most used as you can do anything with it and it was mandatory at client and server side.

**LWM2M v1.1.x** [more or less deprecates TLV](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#7-4-0-74-Data-Formats-for-Transferring-Resource-Information) : 
>  LwM2M Clients supporting LwM2M TS 1.1 or newer SHOULD NOT use the legacy TLV or JSON formats.

And introduces **SenML-CBOR** which is based on **CBOR** described as : 
> The Concise Binary Object Representation (CBOR) is a data format whose design goals include the possibility of extremely small code size, fairly small message size, and extensibility without the need for version negotiation

(source : [RFC8949 § Abstract](https://www.rfc-editor.org/rfc/rfc8949#abstract))

So I guess it should be pretty efficient too but I don't know compare to **TLV**
I suppose that authors add this format because this is an IETF standard (See [RFC8428](https://datatracker.ietf.org/doc/html/rfc8428)) contrary to **TLV** which is LWM2M only ?
(It also seems that [**SenML-CBOR** support timestamped value](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/538#issuecomment-1010149277) but don't know if this is supported by Wakaama)

But the funny part, in **LWM2M v1.2.x** , authors introduce another format called[ **LwM2M CBOR**](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#7-5-4-0-754-LwM2M-CBOR) which is suppose to be more efficient but is NOT an IETF standard and WITHOUT timestamped value support ... (probably not supported by Wakaama because if I remember well Wakaama is about LWM2M v1.1.x )

**Comment by EmbGangsta** [comment]
Thanks again.

I suppose yes that CBOR is efficient too, I will compare the data part when doing a read with TLV and a send with senml CBOR.
Actually I would like to use LWM2M for embedded systems to send binary payloads most of the time ... so I was looking for something efficient !!

I hope the LWM2M standards will converge with something supported by many constructors. Today I am using Wakaama but in the final commercial product maybe we will use the embedded LWM2M stack from modem ...
BTW, what are the legal rules in term of commercial reuse of Wakaama code in a finished sold product ??

**Comment by sbernard31** [comment]
>  BTW, what are the legal rules in term of commercial reuse of Wakaama code in a finished sold product ??

Wakaama is dual licensing so you can choose to use one or another of those 2 licenses : 
 - https://github.com/eclipse/wakaama/blob/main/LICENSE.EPL-2
 - https://github.com/eclipse/wakaama/blob/main/LICENSE.BSD-3-Clause

**Comment by EmbGangsta** [comment]
Thanks.

What is the rule to send unsolicited data using send method without always refreshing connection ?

I noticed that sometimes I have to update registration before to send Coap/CBOR data but sometimes it's not needed ...

Sorry for asking that, I am a rookie in LwM2M ...

De : Simon ***@***.***>
Envoyé : mercredi 20 mars 2024 15:10
À : eclipse/wakaama ***@***.***>
Cc : Panetto David-Alexandre ***@***.***>; Author ***@***.***>
Objet : Re: [eclipse/wakaama] Support of send operation for single resource data with TLV format ? (Issue #761)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://m365.eu.vadesecure.com/safeproxy/v4?f=NoAppMsgH_ERAJfv__0tLF24E33kU8CUIWCKBz_LYxgCmlE2D3pbep9ZnAElTi5Q&i=5ny-Lt5_hnTv8dlh6FvqbxRT3jtH2kpmJ4KDIWuGQUJwOkLefXp-PRoSEatkqTnGsj7TFldDif4ws_gBU4RDYA&k=kSlz&r=pchtF3gk1tLMh_HLowDfBv29toLWnsI1smgahg0izrrzlwaD_DaxrQXgT3N5j8UV&s=108352cde2704709759290b0f746f5074440cb085e4df5b835fcc7efc1851366&u=https%3A%2F%2Faka.ms%2FLearnAboutSenderIdentification>
CAUTION: This message comes from an external server, do not click on links or open attachments unless you know the sender and are sure the content is safe.


BTW, what are the legal rules in term of commercial reuse of Wakaama code in a finished sold product ??

Wakaama is dual licensing so you can choose to use one or another of those 2 licenses :

  *   https://github.com/eclipse/wakaama/blob/main/LICENSE.EPL-2<https://m365.eu.vadesecure.com/safeproxy/v4?f=U21uafJxChxzA0VchrGP4bKQYJUIzIeuQpatQkuZanLb4WflDDkiNgqO2_sjXh6z&i=9Z5cYF8RhijqbBLWu24g50_LeK3k2iIkV7lUGQbSK2uU9yn-l5yLz2omCrrgFUFUeYYVNyJ42Rdslap-C2UFOg&k=71Eg&r=p6IymSogfNeWHq3sODbFpv9Eir8FxKDw6eZYQIBNq9fewXplsqCydMav4jPMVFnK&s=b626a9b63b7ae5637423ad4610965f02f89c7447811df7a644ada304935658ad&u=https%3A%2F%2Fgithub.com%2Feclipse%2Fwakaama%2Fblob%2Fmain%2FLICENSE.EPL-2>
  *   https://github.com/eclipse/wakaama/blob/main/LICENSE.BSD-3-Clause<https://m365.eu.vadesecure.com/safeproxy/v4?f=YqWvvo1Z32-xtnm8gBxc2LTd0y57styuaQ6_-lVvoUi7_5zbfg5U2MWje-oYN2-_&i=Zj6etCQY9VzAaCc2XXAZsvEQnXtlXrTSoGA1FQDoSynJMsEm00ht5z2Taooou3Rm2f1QDGajDUZ7s63WThFzig&k=eV1W&r=A1qf0M-SwYN7p148dwCQmZBRflL5VxqhOtl1Xr9TCmAJMNJIN-IIVr8hiR1kEq7P&s=3c0c59001213e6bd3880568542671eb13b7f23f02f1eb40b756d2763b256cdfc&u=https%3A%2F%2Fgithub.com%2Feclipse%2Fwakaama%2Fblob%2Fmain%2FLICENSE.BSD-3-Clause>

-
Reply to this email directly, view it on GitHub<https://m365.eu.vadesecure.com/safeproxy/v4?f=UQPdVpqM6bKOZVyU58rLdl62-PGVvnWCgnWO30kClifH8BoJIVdNb-Pz389X5k6U&i=gyoHDaYpd-us2LfCLKPsnhEAGoTeKSAfwKp1t5QWNo9LeHgcNe56NhLXObs8NvprQQKnMxKGquhm0ZS7VCovOg&k=tiZG&r=r90C6UAQidSLmXu3v3ckxWuIfnrAnC3y_tCuWXFozvjEAlHuUmxnFuvKXTm-RuWH&s=9e37856f944c315c2033b6f24996b86fc2020cbabc003eef6898e9b1d10526f0&u=https%3A%2F%2Fgithub.com%2Feclipse%2Fwakaama%2Fissues%2F761%23issuecomment-2009664264>, or unsubscribe<https://m365.eu.vadesecure.com/safeproxy/v4?f=VnP7WYmUutwk7azYS7F9F2rf_2tTy6swUfSuPUIZvloWbaGtb7je281JPeDhDIx0&i=H5Qp0swdKVKlFzquvSbvHgV6ucac0S1FvKiHhomIYy7bYFeojo3_VjSAf-iIqrynuFm9DqOYIsJBU8TXtMs0qg&k=Wq2u&r=JCv1LUCNNkUHHhOX5_FGSTmcFRQUH3IgHlQeoDfycC6YYYX0YVmI2opBBjqXj0dg&s=1d3e14de150aeecd70c160447fa10a26514b55f00254013787d28bc4f108297a&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBD3FFPIDCW2N3EFBONDATI3YZGKBVAVCNFSM6AAAAABE7GZX2CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBZGY3DIMRWGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur ou s'il ne vous est pas destiné, merci de le détruire ainsi que toute copie de votre système et d'en avertir immédiatement l'expéditeur. Toute lecture non autorisée, toute utilisation de ce message qui n'est pas conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite. L'Internet ne permettant pas d'assurer l'intégrité de ce message électronique susceptible d'altération, l'expéditeur (et ses filiales) décline(nt) toute responsabilité au titre de ce message dans l'hypothèse où il aurait été modifié ou falsifié.

This message and any attachments (the "message") is intended solely for the intended recipient(s) and is confidential. If you receive this message in error, or are not the intended recipient(s), please delete it and any copies from your systems and immediately notify the sender. Any unauthorized view, use that does not comply with its purpose, dissemination or disclosure, either whole or partial, is prohibited. Since the internet cannot guarantee the integrity of this message which may not be reliable, the sender (and its subsidiaries) shall not be liable for the message if modified or falsified.

**Comment by sbernard31** [comment]
I don't know what you called "connection".

> I noticed that sometimes I have to update registration before to send Coap/CBOR data but sometimes it's not needed ...

Hard to say but maybe you behind NAT and so from a Server point of view your client IP changes and so you need to do an update ?

See : https://github.com/eclipse-leshan/leshan/issues/1544

**Comment by EmbGangsta** [comment]
I am using Wakaama client "update 123" command to refresh the registration.

Maybe it is due to NAT, I don't now, but sometimes if I don't do the "update 123" then the server sends an error response telling I am not registered.

It's not always 1 or 2 minutes, it depends. Is there a session timeout exposed during first registration or registration update ?

De : Simon ***@***.***>
Envoyé : vendredi 22 mars 2024 17:33
À : eclipse/wakaama ***@***.***>
Cc : Panetto David-Alexandre ***@***.***>; Author ***@***.***>
Objet : Re: [eclipse/wakaama] Support of send operation for single resource data with TLV format ? (Issue #761)

CAUTION: This message comes from an external server, do not click on links or open attachments unless you know the sender and are sure the content is safe.


I don't know what you called "connection".

I noticed that sometimes I have to update registration before to send Coap/CBOR data but sometimes it's not needed ...

Hard to say but maybe you behind NAT and so from a Server point of view your client IP changes and so you need to do an update ?

See : eclipse-leshan/leshan#1544<https://m365.eu.vadesecure.com/safeproxy/v4?f=jtp-M6_I1eSup0Ti86MnmezpWs2YQeJeV1GDyf4DsGf-GzmskyAIS02QkzYKN5B_&i=FBdn06er9ksbUfSuY145rzMztHg6ymmwGRspK36qwlXf5dTb5yos_e4mvK1qftmIAdS45vQ_cwykR7SoSJ4s2w&k=DDKQ&r=EgXKhEgSKjGWaQJvJZaQ1dcBHzbCRo7BhXo-dRn6_arccANpBZGSzY0nKdJp-xsJ&s=d30dc36d0a6f3f9e330d9969964109e720017045b1e89b1a35811d37b3de0fc6&u=https%3A%2F%2Fgithub.com%2Feclipse-leshan%2Fleshan%2Fissues%2F1544>

-
Reply to this email directly, view it on GitHub<https://m365.eu.vadesecure.com/safeproxy/v4?f=jU-1FhTZXZd7h2DdFL98Ldhoqw2Ki4KPVKNIY0m3ZZYFUXPQ25IakeaMO68L0RD6&i=iTgkjEcJ--C88Cs2U5rsj3Qu7LFKmfa1iPdEyIiizUiJs0GUBrla4AUv8NKD_Pe6qNnJ1n_eC5HV4eksHa4sUA&k=rg5M&r=foldOSYocQmDOb97QTy42tAXPoRZ6E4V4xTV27YJYvYKINFT7w1vgBntD5T6VXk3&s=fb015181d005638c13695732603df6dcda06f2aa22a7eaa2ed2dfcc8bea8eaa9&u=https%3A%2F%2Fgithub.com%2Feclipse%2Fwakaama%2Fissues%2F761%23issuecomment-2015467384>, or unsubscribe<https://m365.eu.vadesecure.com/safeproxy/v4?f=WDGXo9d3SFvwBptacV27kwjGXTj48-pGuOcYkpZ3r-teW1GNkIGxWcjxd05QT0bP&i=Ai1lZT-vZRDiD7_W9LDCys6sagzp7jjZf2K_-2YxyoGi8pWDk2Lg_jXK5BIGJfRJIt3sjJ6B6t9EnBRvixEPCw&k=8efL&r=Awp1Uu4v9bWhsefbZbDGkhVg5cgeN6CWjnG5_aTWflm-GQED4q5eTwasxSRDvsdU&s=4aeb2324f24b260710d067e457ef48c04af5cb1433d61a237147c9d2afbe98ee&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBD3FFPKW5MPQ5X6LQ4RY4FTYZRMLZAVCNFSM6AAAAABE7GZX2CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJVGQ3DOMZYGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur ou s'il ne vous est pas destiné, merci de le détruire ainsi que toute copie de votre système et d'en avertir immédiatement l'expéditeur. Toute lecture non autorisée, toute utilisation de ce message qui n'est pas conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite. L'Internet ne permettant pas d'assurer l'intégrité de ce message électronique susceptible d'altération, l'expéditeur (et ses filiales) décline(nt) toute responsabilité au titre de ce message dans l'hypothèse où il aurait été modifié ou falsifié.

This message and any attachments (the "message") is intended solely for the intended recipient(s) and is confidential. If you receive this message in error, or are not the intended recipient(s), please delete it and any copies from your systems and immediately notify the sender. Any unauthorized view, use that does not comply with its purpose, dissemination or disclosure, either whole or partial, is prohibited. Since the internet cannot guarantee the integrity of this message which may not be reliable, the sender (and its subsidiaries) shall not be liable for the message if modified or falsified.

**Comment by sbernard31** [comment]
Please read all answers about :  https://github.com/eclipse-leshan/leshan/issues/1544 
And also links provided in those answers.

**Comment by LukasWoodtli** [comment]
@EmbGangsta Can we close this issue? As mentioned by @sbernard31 TLV is not allowed in `send` commands. So we will not implement that in Wakaama. You should probably use SENML CBOR for your case.
