### ISSUE TITLE
Is Leshan ready for production usage ?

### ISSUE THREAD

**Issue by EmbGangsta** [eclipse-wakaama/wakaama#768]
Hi,

Our company (www.cls.fr) is very interested in using LwM2M and we would like to add instance of leshan server inside our infrastructure but I wonder if today leshan is ready to be used in industrial in production mode ?

We need to support LwM2M 1.1 with queue mode as our devices will be sleeping most of the time, will use dynamic IP addresses (devices are using cellular modems).

Then 10000+ beacons could connect at the same time, is Leshan able to cope with this ?

What would be the licensing model in use ?

Regards

**Comment by jvermillard** [comment]
You posted to the wakaama project, I think your question is for the Leshan project

**Comment by EmbGangsta** [comment]
Oh sorry I was in wrong github place, I will post a new request in right place ... please close this one
