### ISSUE TITLE
 Inquiry about CoAP Fetch Functionality Implementation

### ISSUE THREAD

**Issue by jongsu79061** [eclipse-wakaama/wakaama#769]
Hello,

I hope this message finds you well. I am currently exploring the functionalities of CoAP protocol and came across the concept of "fetch"(Code : 0.05). I am curious to know whether the "fetch" functionality is implemented in the Wakaama repository. Could someone please confirm if this feature is available or provide any insights on its implementation status?

Thank you in advance for your assistance!

Best regards,
joon

**Comment by sbernard31** [comment]
I will not be able to answer, so we will wait for active committer to get answer but just to clarify : 

Fetch is a CoAP feature.  
Wakaama is about implementing LWM2M.  
LWM2M used mainly (not only) CoAP as transport layer.  
LWM2M Read Composite, Observe Composite and Active Cancel Composite Request are using CoAP Fetch.  

So I guess your question is : "Does wakaama support those Composite Operation ?"

**Comment by jongsu79061** [comment]
Yes, that's right. I asked you a question because I don't think I can handle the next packet coming in during the test with the lwm2m server using the wakama client.
48 05 00 EB 02 03 A8 26 11 00 11 00 C1 70 51 70
FF 83 A2 21 61 2F 00 67 32 36 31 31 34 2F 30 A1
00 67 32 36 31 31 35 2F 30 A1 00 67 32 36 31 31
36 2F 30
The response from the wakaama client is as follows.
60 00 00 EB

**Comment by LukasWoodtli** [comment]
CoAP fetch is not implemented in Wakaama. Feel free to contribute.
There have also been ideas to implement an abstraction layer for CoAP libraries to be more flexible regarding CoAP implementations.
