### ISSUE TITLE
Include other libraries in examples

### ISSUE THREAD

**Issue by Pmctst** [eclipse-wakaama/wakaama#776]
I know this is not an issue but a lack of knowledge on my side.
I have not worked with CMAKE in the past and I have no idea where to include another library. I want to make a quick sample code based on the server application including mysql library.

I don't know where I have to include the -I and -L attributes before executing cmake so make order links all the files.

**Comment by LukasWoodtli** [comment]
You would use [target_link_libraries](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) and [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html).
This is a general CMake problem and not related to Wakaama. So maybe learn some CMake basics first.
[This](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html) is a concise description of CMake. But it might be a bit difficult to understand for a CMake beginner. So you might want to just start with a tutorial.
